### ISSUE TITLE
Hardwired exclusive index in Serial mode

### ISSUE THREAD

**Issue by stgeke** [libocca/occa#488] opened 2021-03-15 13:44 UTC
https://github.com/libocca/occa/blob/main/src/occa/internal/lang/modes/serial.cpp#L283
Instead of using a hardwired value I would expect it to match the inner loop dimensions.

**Comment by dmed256** [comment] 2021-03-15 22:37
Duplicate of #121, thank you for bringing this back up

**Closed** 2022-05-20 21:20 UTC
