### ISSUE TITLE
libocca compilation error involving Metal

### ISSUE THREAD

**Issue by jlchan** [libocca/occa#250] opened 2019-09-11 17:30 UTC
Compiling from a fresh clone gives the following errors related to the new Metal API.

> /Users/jchan985/Desktop/occa/src/api/metal/commandQueue.mm:62:12: error: no type or protocol named 'MTLEvent'
>         id<MTLEvent> event = [metalDevice newEvent];
>            ^
> /Users/jchan985/Desktop/occa/src/api/metal/commandQueue.mm:62:43: warning: instance method '-newEvent' not found
>       (return type defaults to 'id') [-Wobjc-method-access]
>         id<MTLEvent> event = [metalDevice newEvent];
>                                           ^~~~~~~~
> 1 warning and 1 error generated.
> make: *** [/Users/jchan985/Desktop/occa/obj/api/metal/commandQueue.o] Error 1
> make: *** Waiting for unfinished jobs....
> /Users/jchan985/Desktop/occa/src/api/metal/device.mm:37:29: warning: instance method '-recommendedMaxWorkingSetSize' not found
>       (return type defaults to 'id') [-Wobjc-method-access]
>         return [metalDevice recommendedMaxWorkingSetSize];
>                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/jchan985/Desktop/occa/src/api/metal/device.mm:37:16: error: cannot initialize return object of type 'udim_t'
>       (aka 'unsigned long long') with an rvalue of type 'id'
>         return [metalDevice recommendedMaxWorkingSetSize];

**Comment by dmed256** [comment] 2019-09-16 16:06
Drat, I need to probably check the Metal version before enabling it. Thanks for the report!

**Comment by dmed256** [comment] 2021-01-17 18:42
Unable to reproduce, closing for now :disappointed:

**Closed by dmed256** 2021-01-17 18:42 UTC
Labels: Metal, bug
