### ISSUE TITLE
segfaults

### ISSUE THREAD

**Issue by igory1999** [libocca/occa#253] opened 2019-10-09 17:52 UTC
No matter what I do with occa, at the end it segfaults. For example:

$ bin/occa info
   
     CPU(s) | Processor Name       | Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz 
            | Cores                | 8                                         
            | Memory (RAM)         | 31.23 GB                                  
            | Clock Frequency      | 2.7 GHz                                   
            | SIMD Instruction Set | SSE2                                      
            | SIMD Width           | 128 bits                                  
            | L1 Cache Size (d)    |   32K                                     
            | L2 Cache Size        |  256K                                     
            | L3 Cache Size        | 6144K                                     
    ========+======================+===========================================
     OpenCL | Device Name          | GeForce GTX 960M                          
            | Driver Vendor        | NVIDIA                                    
            | Platform ID          | 0                                         
            | Device ID            | 0                                         
            | Memory               | 1.95 GB                                   
            |----------------------+-------------------------------------------
            | Device Name          | Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz 
            | Driver Vendor        | Intel                                     
            | Platform ID          | 1                                         
            | Device ID            | 0                                         
            | Memory               | 31.23 GB                                  
    ========+======================+===========================================
     CUDA   | Device Name          | GeForce GTX 960M                          
            | Device ID            | 0                                         
            | Memory               | 1.95 GB                                   
    ========+======================+===========================================
Segmentation fault (core dumped)

My system is Ubuntu 18.04
I used the default gcc 7.4.0 to compile it by running make. I did not modify Makefile.

nvidia-smi
Wed Oct  9 13:51:00 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |

**Comment by dmed256** [comment] 2019-10-09 23:30
@igory1999 Thanks for the bug report! I'm unable to reproduce this, do you mind helping me debug this issue?

If yes, can you try the following:

**Avoid compiling OpenCL Backend**
```bash
export OCCA_OPENCL_ENABLED=0
make clean
make
```

**Avoid compiling CUDABackend**
```bash
export OCCA_CUDA_ENABLED=0
make clean
make
```

I'm not sure if some backend destructors is complaining at the end of calling `occa info`.

**Comment by igory1999** [comment] 2019-10-10 03:31
Hi David,
Disabling OpenCL fixed the problem.
The only two examples that are still failing: Unified memory and MPI.
Perhaps, my GPU card does not support Unified memory and apparently
something needs to be done for MPI (should OCCA be compiled with MPI
support?).
I tried
CXX=mpic++ make
or
OCCA_CXX=mpic++ make
but so far it did not work.
Thank you,
Igor

**Comment by dmed256** [comment] 2019-10-10 03:47
Hi Igor,

Thanks for investigating further! 

**OpenCL**
Weird, I'll see if I can get someone around me to reproduce it and debug it. Thanks for the info!

**Unified Memory**
The unified memory is emulated by OCCA, strange it doesn't work. Can you post the error?

**MPI**
OCCA and the example need to be compiled with MPI. Can you try a `make clean` and recompiling with 
```
CXX=mpic++ make
```

I can add an error message in the MPI example so it's less confusing.

David

**Comment by igory1999** [comment] 2019-10-10 03:55
Hi David,
On second attempt unified memory example worked.
Can one use MPI with a single GPU card and multiple ranks? I built OCCA
with MPI support and now MPI example compiles but cannot run because it
requires 2 ranks and each MPI rank tries to grab the whole card. I vaguely
remember that there is some environmental variable that might allow to
share the card.
Thank you,
Igor

**Comment by dmed256** [comment] 2019-10-10 04:07
Hi Igor,

**Unified Memory**
Nice!

**MPI**
The example is meant for 2 ranks, the first rank using OpenMP and the second with CUDA
```cpp
  occa::json config = occa::json::parse(
    "["
    "  { mode: 'OpenMP' },"
    "  { mode: 'CUDA', device_id: 0 },"
    "]"
  );
```

If you want to run with CUDA and 2 devices, you can use
```cpp
  occa::json config = occa::json::parse(
    "["
    "  { mode: 'CUDA', device_id: 0 },"
    "  { mode: 'CUDA', device_id: 1 },"
    "]"
  );
```

**Comment by dmed256** [comment] 2019-10-10 05:22
With a lot of help from @artv3, we found out the segfault issue is coming from a weird Intel OpenCL bug.

![image](https://user-images.githubusercontent.com/1812355/66541106-00003480-eae3-11e9-917f-38ced5f75ab0.png)

OpenCL reads files inside 

```
/etc/OpenCL/vendors/*.icd
```

and `dlopen`s the `.so` files in the `.icd` file contents. It seems when the program ends, the `dlopen`-ed `.so` doesn't close properly leading to a segfault. 

I'm closing this issue since #251 has the same bug but feel free to ask more questions here or in another issue. Same if you find more bugs, thank you again!

**Closed by dmed256** 2019-10-10 05:22 UTC
Labels: bug
