### ISSUE TITLE
Fatal crash in destructor call for kernels with multiple outer loop blocks

### ISSUE THREAD

**Issue by tcew** [libocca/occa#393] opened 2020-08-05 14:00 UTC
Using this kernel in the addVectors cpp example results in a seg fault, 

```
@kernel void multiKernels(const int entries,
                          const float *x,
                          float *y,
                          float *z) {

#define B 256
  
  for(int b=0;b<(entries+B-1)/B;++b;@outer){
    for(int t=0;t<B;++t;@inner){
      int n = t+b*B;
      if(n<entries)
        y[n] = x[n];
    }
  }

  for(int b=0;b<(entries+B-1)/B;++b;@outer){
    for(int t=0;t<B;++t;@inner){
      int n = t+b*B;
      if(n<entries)
        z[n] = y[n];
    }
  }
}
```

The kernel destructor appears to be called more than once.

**Comment by dmed256** [comment] 2021-01-21 06:31
I can't seem to reproduce, maybe it was fixed since then?

I tried replacing `addVectors.okl` with `multiKernels.okl` and didn't have issues on `Serial` or `CUDA` modes. 

Closing for now but we can open it again if it's still an issue!

**Closed by dmed256** 2021-01-21 06:31 UTC
