### ISSUE TITLE
Add a 'contrib' directory and written guidelines for user contributions

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#189] opened 2018-08-09 13:28 UTC
I would consider submitting some "example"-type code as a contribution if there were a mechanism for doing so. Such a mechanism could help grow use of OCCA.

You (or a committee) must review the contributions, which must be submitted for review and approval, in order to avoid problems.

I suggest that you also have written guidelines especially in regards to licensing (e.g., MIT). Note the licensing should allow for recognition of the contributor, and include the usual legalese about "fitness of use" and "performance".

Guidelines should also be explicit about what is acceptable and what is not acceptable.

**Comment by pdhahn** [comment] 2018-08-09 13:34
Of course, you could just consider a potential user contribution for inclusion in the existing examples directory. However, a "contrib" mechanism differs from "examples" not only in terms of (nuanced) tone and perception, but also as an "acceptance" mechanism with procedures and written guidelines. This is why I said it might help grow use of OCCA over time.

**Comment by pdhahn** [comment] 2018-08-10 13:48
BTW what I have in mind to contribute is a naive/non-optimized version in OKL of a many-matrix inverter based on parallelized Gaussian elimination with scaling + row pivoting. It may be useful in terms of performance when the number of matrices on which it operates is large, or when the number of matrices is modest but the matrix dimension is large (notwithstanding the usual numerical issues). I actually use something similar to it (but a bit more advanced) in my company's application code.

**Comment by pdhahn** [comment] 2018-08-10 20:11
You are right, it should `not` be a part of the code base. Disclaimers like "no support or maintenance provided" and "use at your own risk" are characteristics of a "contrib" section, vs. an "examples" section (which is supported / maintained and part of the code base). That is why I made this suggestion, to have something that is separate from "examples" yet still accessible in a common place for convenience to users.

So a separate area similar to the gallery section would work fine. Not sure I would call it a "libraries section", though. I think that "contrib[utions] section" would be better.

**Comment by pdhahn** [comment] 2018-08-10 20:17
And indeed the idea I am advocating is something that could encourage sharing of re-usable **OKL** code specifically, or at least primarily.

**Comment by dmed256** [comment] 2019-07-06 02:32
Duplicate of #231

**Closed by dmed256** 2019-07-06 02:32 UTC
Labels: question

**Comment by pdhahn** [comment] 2019-07-06 17:22
I do not agree this is a duplicate of #231. The notions of "contribution" are different in the context of this issue vs. that issue. In this issue, a "contribution" really just means _user_-created OKL code, more like "examples". In #231, "contribution" means work by an interested _developer_ to implement an open feature request more oriented towards modification of OCCA internals.

All that said, I do not object to closing this issue, just not on the basis of it being a duplicate.

Thanks for OCCA!
